# Generated by Django 4.2.7 on 2023-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField()),
                ('nome_estadia', models.CharField(max_length=200)),
                ('descricao_estadia', models.CharField(max_length=1000)),
                ('localizacao', models.CharField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
                ('programacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='filomenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.IntegerField()),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('profissao', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao_produto', models.CharField(max_length=1000)),
            ],
        ),
    ]
