# Generated by Django 4.2.3 on 2023-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filomenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='filomenas',
            name='imagem_filo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hospede',
            name='imagem_perfil',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
