# Generated by Django 4.2.7 on 2023-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filomenas', '0002_estadia_imagem_filomenas_imagem_filo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filomenas',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='programacao',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
