# Generated by Django 4.2.7 on 2023-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filomenas', '0003_filomenas_email_alter_estadia_programacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filomenas',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
